/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VehiclesTypesRecord extends org.jooq.impl.TableRecordImpl<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

    private static final long serialVersionUID = -2013143456;

    /**
     * Setter for <code>PUBLIC.VEHICLES_TYPES.ID</code>.
     */
    public void setId(java.lang.Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>PUBLIC.VEHICLES_TYPES.ID</code>.
     */
    public java.lang.Long getId() {
        return (java.lang.Long) getValue(0);
    }

    /**
     * Setter for <code>PUBLIC.VEHICLES_TYPES.DESC</code>.
     */
    public void setDesc(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>PUBLIC.VEHICLES_TYPES.DESC</code>.
     */
    public java.lang.String getDesc() {
        return (java.lang.String) getValue(1);
    }

    /**
     * Setter for <code>PUBLIC.VEHICLES_TYPES.NAME</code>.
     */
    public void setName(java.lang.String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>PUBLIC.VEHICLES_TYPES.NAME</code>.
     */
    public java.lang.String getName() {
        return (java.lang.String) getValue(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
        return (org.jooq.Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
        return (org.jooq.Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field1() {
        return br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field3() {
        return br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesTypesRecord value1(java.lang.Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesTypesRecord value2(java.lang.String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesTypesRecord value3(java.lang.String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesTypesRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiclesTypesRecord
     */
    public VehiclesTypesRecord() {
        super(br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES);
    }

    /**
     * Create a detached, initialised VehiclesTypesRecord
     */
    public VehiclesTypesRecord(java.lang.Long id, java.lang.String desc, java.lang.String name) {
        super(br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES);

        setValue(0, id);
        setValue(1, desc);
        setValue(2, name);
    }
}
