/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
		comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VehiclesRecord extends org.jooq.impl.UpdatableRecordImpl<br.com.crud.vehicles.db.tables.records.VehiclesRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1487767889;

	/**
	 * Setter for <code>PUBLIC.VEHICLES.ID</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.VEHICLES.ID</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.VEHICLES.DESC</code>.
	 */
	public void setDesc(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.VEHICLES.DESC</code>.
	 */
	public java.lang.String getDesc() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.VEHICLES.ID_VEHICLE_TYPE</code>.
	 */
	public void setIdVehicleType(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.VEHICLES.ID_VEHICLE_TYPE</code>.
	 */
	public java.lang.Long getIdVehicleType() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.VEHICLES.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.VEHICLES.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.VEHICLES.PLATE</code>.
	 */
	public void setPlate(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.VEHICLES.PLATE</code>.
	 */
	public java.lang.String getPlate() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.ID_VEHICLE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.PLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getIdVehicleType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPlate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord value2(java.lang.String value) {
		setDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord value3(java.lang.Long value) {
		setIdVehicleType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord value5(java.lang.String value) {
		setPlate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VehiclesRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VehiclesRecord
	 */
	public VehiclesRecord() {
		super(br.com.crud.vehicles.db.tables.Vehicles.VEHICLES);
	}

	/**
	 * Create a detached, initialised VehiclesRecord
	 */
	public VehiclesRecord(java.lang.Long id, java.lang.String desc, java.lang.Long idVehicleType, java.lang.String name, java.lang.String plate) {
		super(br.com.crud.vehicles.db.tables.Vehicles.VEHICLES);

		setValue(0, id);
		setValue(1, desc);
		setValue(2, idVehicleType);
		setValue(3, name);
		setValue(4, plate);
	}
}
