/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
		comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Vehicles extends org.jooq.impl.TableImpl<br.com.crud.vehicles.db.tables.records.VehiclesRecord> {

	private static final long serialVersionUID = -1163633060;

	/**
	 * The singleton instance of <code>PUBLIC.VEHICLES</code>
	 */
	public static final br.com.crud.vehicles.db.tables.Vehicles VEHICLES = new br.com.crud.vehicles.db.tables.Vehicles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<br.com.crud.vehicles.db.tables.records.VehiclesRecord> getRecordType() {
		return br.com.crud.vehicles.db.tables.records.VehiclesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.VEHICLES.ID</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES.DESC</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesRecord, java.lang.String> DESC = createField("DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES.ID_VEHICLE_TYPE</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesRecord, java.lang.Long> ID_VEHICLE_TYPE = createField("ID_VEHICLE_TYPE", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES.NAME</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES.PLATE</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesRecord, java.lang.String> PLATE = createField("PLATE", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>PUBLIC.VEHICLES</code> table reference
	 */
	public Vehicles() {
		this("VEHICLES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.VEHICLES</code> table reference
	 */
	public Vehicles(java.lang.String alias) {
		this(alias, br.com.crud.vehicles.db.tables.Vehicles.VEHICLES);
	}

	private Vehicles(java.lang.String alias, org.jooq.Table<br.com.crud.vehicles.db.tables.records.VehiclesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Vehicles(java.lang.String alias, org.jooq.Table<br.com.crud.vehicles.db.tables.records.VehiclesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, br.com.crud.vehicles.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<br.com.crud.vehicles.db.tables.records.VehiclesRecord> getPrimaryKey() {
		return br.com.crud.vehicles.db.Keys.CONSTRAINT_A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<br.com.crud.vehicles.db.tables.records.VehiclesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<br.com.crud.vehicles.db.tables.records.VehiclesRecord>>asList(br.com.crud.vehicles.db.Keys.CONSTRAINT_A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public br.com.crud.vehicles.db.tables.Vehicles as(java.lang.String alias) {
		return new br.com.crud.vehicles.db.tables.Vehicles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public br.com.crud.vehicles.db.tables.Vehicles rename(java.lang.String name) {
		return new br.com.crud.vehicles.db.tables.Vehicles(name, null);
	}
}
