/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
		comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VehiclesTypes extends org.jooq.impl.TableImpl<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord> {

	private static final long serialVersionUID = -1898375084;

	/**
	 * The singleton instance of <code>PUBLIC.VEHICLES_TYPES</code>
	 */
	public static final br.com.crud.vehicles.db.tables.VehiclesTypes VEHICLES_TYPES = new br.com.crud.vehicles.db.tables.VehiclesTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord> getRecordType() {
		return br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.VEHICLES_TYPES.ID</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES_TYPES.DESC</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord, java.lang.String> DESC = createField("DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.VEHICLES_TYPES.NAME</code>.
	 */
	public final org.jooq.TableField<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>PUBLIC.VEHICLES_TYPES</code> table reference
	 */
	public VehiclesTypes() {
		this("VEHICLES_TYPES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.VEHICLES_TYPES</code> table reference
	 */
	public VehiclesTypes(java.lang.String alias) {
		this(alias, br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES);
	}

	private VehiclesTypes(java.lang.String alias, org.jooq.Table<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private VehiclesTypes(java.lang.String alias, org.jooq.Table<br.com.crud.vehicles.db.tables.records.VehiclesTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, br.com.crud.vehicles.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public br.com.crud.vehicles.db.tables.VehiclesTypes as(java.lang.String alias) {
		return new br.com.crud.vehicles.db.tables.VehiclesTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public br.com.crud.vehicles.db.tables.VehiclesTypes rename(java.lang.String name) {
		return new br.com.crud.vehicles.db.tables.VehiclesTypes(name, null);
	}
}
