/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db;

/**
 * This class is generated by jOOQ.
 * <p>
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code>
 * schema
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final org.jooq.UniqueKey<br.com.crud.vehicles.db.tables.records.VehiclesRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
        public static final org.jooq.UniqueKey<br.com.crud.vehicles.db.tables.records.VehiclesRecord> CONSTRAINT_A = createUniqueKey(br.com.crud.vehicles.db.tables.Vehicles.VEHICLES, br.com.crud.vehicles.db.tables.Vehicles.VEHICLES.ID);
    }
}
