/**
 * This class is generated by jOOQ
 */
package br.com.crud.vehicles.db;

/**
 * This class is generated by jOOQ.
 * <p>
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table PUBLIC.VEHICLES_TYPES
     */
    public static final br.com.crud.vehicles.db.tables.VehiclesTypes VEHICLES_TYPES = br.com.crud.vehicles.db.tables.VehiclesTypes.VEHICLES_TYPES;

    /**
     * The table PUBLIC.VEHICLES
     */
    public static final br.com.crud.vehicles.db.tables.Vehicles VEHICLES = br.com.crud.vehicles.db.tables.Vehicles.VEHICLES;
}
